AllCops:
  TargetRubyVersion: 3.4
  Exclude:
    - 'test/fixtures/**/*'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
